(function(){'use strict';
const ID='Y3-012-Essay', NAME='Essay Studio', DB='Y3_012_EssayDB'; let root=null, db=null, state=null, timers=[];
const $=(s)=>root&&root.querySelector(s), $$=(s)=>root?[...root.querySelectorAll(s)]:[];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
function base(){return{id:uid(),title:'',subject:'Pathology',question:'',essay:'',plan:'',createdAt:Date.now(),updatedAt:Date.now(),versions:[],score:null,reviewCount:0,nextReview:0,tags:[]}}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('essays'))d.createObjectStore('essays',{keyPath:'id'});if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta',{keyPath:'key'});if(!d.objectStoreNames.contains('reviews'))d.createObjectStore('reviews',{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function put(store,obj){return new Promise((r,j)=>{const q=tx(store,'readwrite').put(obj);q.onsuccess=()=>r();q.onerror=()=>j(q.error)})}
function all(store){return new Promise((r,j)=>{const q=tx(store).getAll();q.onsuccess=()=>r(q.result||[]);q.onerror=()=>j(q.error)})}
function del(store,id){return new Promise((r,j)=>{const q=tx(store,'readwrite').delete(id);q.onsuccess=()=>r();q.onerror=()=>j(q.error)})}
function val(id){const e=$('#'+id);return e?e.value:''} function set(id,v){const e=$('#'+id);if(e)e.value=v||''}
function sync(){set('title',state.title);set('subject',state.subject);set('question',state.question);set('editor',state.essay);$('#planView').textContent=state.plan||'No plan yet. Use Plan or Build outline.';stats();}
function stats(){const t=val('editor').trim(), w=t?t.split(/\s+/).length:0;$('#words').textContent=w;$('#chars').textContent=t.length;$('#paras').textContent=t?t.split(/\n\s*\n/).filter(Boolean).length:0;$('#readTime').textContent=Math.max(0,Math.ceil(w/200))+' min'}
function capture(){state.title=val('title').trim();state.subject=val('subject');state.question=val('question').trim();state.essay=val('editor');state.updatedAt=Date.now()}
let saveDebounce;function autosave(){capture();$('#saveState').textContent='Saving…';clearTimeout(saveDebounce);saveDebounce=setTimeout(async()=>{try{await put('essays',state);$('#saveState').textContent='Saved';await refresh()}catch(e){$('#saveState').textContent='Error'}},350)}
async function refresh(){const xs=await all('essays');$('#essayCount').textContent=xs.length;const reviewed=xs.filter(x=>x.score!=null);$('#reviewCount').textContent=reviewed.length;$('#avgScore').textContent=reviewed.length?(reviewed.reduce((a,x)=>a+Number(x.score||0),0)/reviewed.length).toFixed(1)+'/100':'—';$('#dueCount').textContent=xs.filter(x=>x.nextReview&&x.nextReview<=Date.now()).length;const recent=xs.sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,8);$('#recent').innerHTML=recent.map(x=>`<div class="item" data-load="${x.id}"><b>${esc(x.title||'Untitled essay')}</b><div class="muted">${esc(x.subject)} · ${new Date(x.updatedAt).toLocaleDateString()}</div></div>`).join('')||'<span class="muted">No saved essays yet.</span>'}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function context(task,extra=''){return`Module: ${ID} (${NAME})\nSubject: ${state.subject}\nQuestion: ${state.question}\nEssay:\n${state.essay}\nTask: ${task}\nAdditional context: ${extra}`}
async function ask(task,extra=''){if(!window.year3||!window.year3.ai||typeof window.year3.ai.ask!=='function'){showAI('AI bridge is unavailable. Check CORE/preload.js and the host AI IPC bridge.');return null}capture();const msg=context(task,extra);$('#aiStatus').textContent='AI is working…';try{const r=await window.year3.ai.ask({message:msg,context:{moduleId:ID,moduleName:NAME,subject:state.subject,topic:state.title,question:state.question,essay:state.essay,task}});const text=typeof r==='string'?r:(r?.text||r?.response||r?.content||JSON.stringify(r,null,2));showAI(text||'No AI response returned.');$('#aiStatus').textContent='AI response ready';return text}catch(e){showAI('AI request failed: '+(e?.message||e));$('#aiStatus').textContent='AI error';return null}}
function showAI(t){$('#aiResult').textContent=t||''}
function modal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#overlay').classList.remove('hidden')}
function closeModal(){$('#overlay').classList.add('hidden')}
function newEssay(){state=base();sync();showAI('New essay ready. Enter a question or ask AI Question.');}
async function load(id){const xs=await all('essays');const x=xs.find(a=>a.id===id);if(x){state=x;sync();showAI('Loaded “'+(x.title||'Untitled essay')+'”.')}}
async function aiQuestion(){const text=await ask('Generate one Year 3 medical essay question. Give the question, subject, command word, difficulty, learning objectives, and a concise marking focus. Do not write the answer.');if(text) set('question',text.split('\n')[0].replace(/^.*?:\s*/,''));autosave()}
async function plan(){const t=await ask('Act as an essay tutor. Build a high-yield plan for this question: command word interpretation, thesis/central position, introduction components, 4–7 body sections with key points and clinical links, and conclusion. Do not write the final essay.');if(t){state.plan=t;$('#planView').textContent=t;await put('essays',state);}}
async function mark(){const t=await ask('Act as a strict but fair medical-school examiner. Mark the essay against relevance, structure, factual accuracy, depth, mechanisms, clinical application, terminology, and conclusion. Return: estimated score /100, strengths, missing points, factual issues, paragraph-level improvements, and a short priority action list. Do not rewrite the whole essay.');if(t){state.reviewCount=(state.reviewCount||0)+1;state.nextReview=Date.now()+7*86400000;const m=t.match(/(?:score|mark|total)[^\d]{0,20}(\d{1,3})\s*\/\s*100/i);if(m)state.score=Number(m[1]);await put('essays',state);await refresh()}}
async function teach(){await ask('Teach me this question from first principles at Year 3 medical level. Explain what the examiner expects, prerequisite concepts, a logical reasoning pathway, common traps, and a mini self-test. Do not produce a submission-ready essay.');}
async function quick(kind){const prompts={analyze:'Analyze my essay for structure, relevance, depth and medical reasoning. Give actionable feedback only.',gaps:'Find important missing points expected in a strong Year 3 answer. Prioritize high-yield omissions.',improve:'Coach me on clarity, academic style, terminology, transitions and concise medical writing. Give examples of short local improvements, not a full rewrite.',outline:'Create a concise answer outline based on the exact question and command word. Do not write the full answer.',command:'Identify the command word and explain exactly what it requires me to do and what it does not require.',intro:'Coach me to construct a strong introduction: context, definition where needed, scope and thesis. Give a framework and critique my current introduction if present.',conclusion:'Coach me to build a conclusion that answers the question, synthesizes key points and avoids new evidence.',clinical:'Identify appropriate clinical correlations and explain where they strengthen the essay.',viva:'Act as a viva examiner. Ask one question at a time based on this essay and wait for my answer.',flashcards:'Create high-yield flashcard prompts from my essay. Questions only first; avoid simply copying sentences.',mcqs:'Create 5 Year 3 medical MCQs testing the concepts in my essay. Include answers and brief rationales.',notes:'Convert the essay into structured revision notes with headings, mechanisms, clinical links and high-yield takeaways.'};await ask(prompts[kind]||kind)}
function version(){capture();state.versions=state.versions||[];state.versions.push({at:Date.now(),essay:state.essay,title:state.title});if(state.versions.length>30)state.versions.shift();put('essays',state);modal('Version history',state.versions.slice().reverse().map((v,i)=>`<div class="item"><b>${new Date(v.at).toLocaleString()}</b><p>${esc(v.essay.slice(0,300))}</p><button data-version="${state.versions.length-1-i}">Restore</button></div>`).join('')||'<p>No versions yet.</p>')}
async function library(){const xs=await all('essays');modal('Essay library',`<div class="list">${xs.map(x=>`<div class="item"><b>${esc(x.title||'Untitled')}</b><div>${esc(x.subject)} · ${x.score!=null?x.score+'/100':'Not marked'}</div><button data-load="${x.id}">Open</button> <button class="danger" data-delete="${x.id}">Delete</button></div>`).join('')||'<p>No essays saved.</p>'}</div>`)}
function questions(){modal('Question bank',`<p>Generate targeted questions with AI.</p><div class="actions"><button data-q="Pathology">Pathology</button><button data-q="Pharmacology">Pharmacology</button><button data-q="Microbiology">Microbiology</button><button data-q="Obstetrics & Gynaecology">Obstetrics & Gynaecology</button><button data-q="Integrated">Integrated</button></div><p class="muted">Choose a subject, then AI will create an exam-style question without writing your answer.</p>`)}
async function generate(sub){set('subject',sub);await ask('Generate 5 varied Year 3 medical essay questions for '+sub+'. Mix describe, explain, discuss, compare and critically discuss. Include difficulty and a one-line marking focus. Do not provide model answers.');closeModal()}
async function past(){modal('Past-paper analyzer','<p>Paste a past-paper question set below. The AI will identify recurring themes, command words, topic frequency, difficulty and revision priorities.</p><textarea id="pastText" style="width:100%;min-height:240px" placeholder="Paste questions here..."></textarea><div class="actions" style="margin-top:8px"><button id="pastRun" class="primary">Analyze with AI</button></div>');$('#pastRun').onclick=async()=>{const p=$('#pastText').value;closeModal();await ask('Analyze this past paper for recurring topics, command words, likely high-yield areas, difficulty and a prioritized revision plan. Do not invent frequencies.\n\nPAST PAPER:\n'+p)} }
function exam(){capture();let seconds=45*60, active=true;modal('Exam mode',`<div class="exam"><p><b>AI assistance is disabled while the exam timer is running.</b></p><div class="timer" id="examTimer">45:00</div><p>Question: ${esc(state.question||'No question yet')}</p><button id="submitExam" class="primary">Submit exam</button></div>`);const tick=setInterval(()=>{if(!active){clearInterval(tick);return}seconds--;const e=$('#examTimer');if(e)e.textContent=Math.floor(seconds/60).toString().padStart(2,'0')+':'+(seconds%60).toString().padStart(2,'0');if(seconds<=0){active=false;closeModal();mark()}},1000);timers.push(tick);$('#submitExam').onclick=()=>{active=false;clearInterval(tick);closeModal();mark()}}
function writingTimer(){let s=0;modal('Writing timer','<div class="timer" id="writeTimer">00:00</div><button id="stopWrite">Stop</button>');const t=setInterval(()=>{s++;const e=$('#writeTimer');if(e)e.textContent=Math.floor(s/60).toString().padStart(2,'0')+':'+(s%60).toString().padStart(2,'0')},1000);timers.push(t);$('#stopWrite').onclick=()=>{clearInterval(t);closeModal()}}
function ioExport(){capture();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.title||'essay').replace(/[^\w-]+/g,'_')+'.json';a.click();URL.revokeObjectURL(a.href)}
function ioImport(){const f=$('#fileInput');f.value='';f.click();f.onchange=async()=>{const file=f.files?.[0];if(!file)return;try{const txt=await file.text();const x=JSON.parse(txt);state={...base(),...x,id:x.id||uid(),updatedAt:Date.now()};await put('essays',state);sync();await refresh()}catch(e){alert('Could not import this file. Use a JSON export from Essay Studio.')}}}
function bind(){['title','question','editor'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{if(id==='editor')stats();autosave()}));$('#subject')?.addEventListener('change',autosave);$('#newBtn').onclick=newEssay;$('#questionBtn').onclick=aiQuestion;$('#planBtn').onclick=plan;$('#teachBtn').onclick=teach;$('#markBtn').onclick=mark;$('#examBtn').onclick=exam;$('#themeBtn').onclick=()=>document.documentElement.classList.toggle('dark');$('#timerBtn').onclick=writingTimer;$('#historyBtn').onclick=version;$('#libraryBtn').onclick=library;$('#questionBankBtn').onclick=questions;$('#pastPaperBtn').onclick=past;$('#generateBtn').onclick=()=>questions();$('#exportBtn').onclick=ioExport;$('#importBtn').onclick=ioImport;$('#closeModal').onclick=closeModal;$('#overlay').addEventListener('click',e=>{if(e.target.id==='overlay')closeModal()});$$('[data-ai]').forEach(b=>b.onclick=()=>quick(b.dataset.ai));$('#recent').addEventListener('click',e=>{const b=e.target.closest('[data-load]');if(b)load(b.dataset.load)});document.addEventListener('keydown',keyHandler);}
function keyHandler(e){if(!root)return;if(e.key==='Escape')closeModal();if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();autosave()}if(e.ctrlKey&&e.key==='Enter'){e.preventDefault();quick('analyze')}}
async function init(){if(root)return;root=document.getElementById('essayRoot');if(!root)return;try{await openDB();const xs=await all('essays');state=xs.sort((a,b)=>b.updatedAt-a.updatedAt)[0]||base();sync();bind();await refresh()}catch(e){showAI('Essay storage could not initialize: '+e.message)}}
function destroy(){timers.forEach(clearInterval);timers=[];document.removeEventListener('keydown',keyHandler);clearTimeout(saveDebounce);root=null;db=null;state=null}
window.EssayModule={init,destroy};if(document.getElementById('essayRoot'))init();
})();
